### ISSUE TITLE
Current (1.0.0) pypi release is broken

### ISSUE THREAD

**Issue by toolness** [18F/cg-django-uaa#26]
Something like this appears when trying to `pip install` it:

```pytb
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/jq/6khlmd0d7hz6jpng_pcqvzr40000gp/T/pip-build-ukvl_6bh/cg-django-uaa/setup.py", line 106, in <module>
        tests_require=open('requirements-tests.txt', 'r').read().\
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements-tests.txt'
```

**Comment by toolness** [comment]
Fixed by #27. Cutting a new release now...
